import LocalizedStrings from 'react-localization';

let languageStrings = new LocalizedStrings({
 en:{
   dashboard:"Dashboard",
   cmr_photo:'CMR photo',
   agent_name:"Agent name",
   customer_name:"Customer name",
   customers:"Customers",
   export:'Export',
   agent_and_customer:'Agent and Customer',
   vehicles:"Vehicles",
   export_to_transit:"Export To Transit",
   export_to_destination:"Export To Destination",
   created_at:'Created At',
   created_by:'Created By',
   accounting:"Accounting",
   settings:"Settings",
   galaxy_ports:"Galaxy Ports",
   vehicle_search_by_vin:"Vehicle search by Vin/Lot/Container No",
   locations : "Locations",
   countries : "Countries",
   states : "States",
   cities : "Cities",
   roles : "Roles",
   user_management : "User Management",
   port_of_loading : "Port of Loading",
   port_of_discharge : "Port of Discharge",
   vehicle_status : "Vehicle Status",
   location : "Location",
   all_vehicle : "All Vehicle",
   arrived_to_destination : "Arrived to Destination",
   arrived_to_transit : "Arrived to Transit",
   inside_the_port : "Inside The Port",
   car_on_hand : "Car On Hand",
   shipped_to_transit : "Shipped To Transit",

   customer_global_search : "Customer Global Search",
   search : "Search",
   add_new : "Add New",
   export_customer : "Export Customer",
   customer_id	 : "Customer Id	",
   name	 : "Name",
   company_name	 : "Company Name",
   email	 : "Email",
   phone_uae	 : "Phone UAE",
   city	 : "City",
   status	 : "Status",
   total_vehicles	 : "Total Vehicles",
   action	 : "Action",
   note_allow_show	 : "You are not allowed to view this page",
   
   export_vehicles : "Export Vehicls",
   notes : "Notes",
   vehicle_global_search : "Vehicle Global Search",
   photo : "Photo",
   total_photos : "Total Photos",
   add : "Add",
   req_date : "REQ DATE",
   pickup_date : "PICKUP DATE",
   dely_date : "DELY DATE",
   received_date : "Received Date",
   days : "Days",
   year : "Year",
   make : "Make",
   model : "Model",
   color : "Color",
   vin : "Vin",
   lot_number : "Lot Number",
   keys : "Keys",
   vehicle_type : "Vehicle Type",
   created_date : "Created Date",
   note : "Note",

   vehicle_create : "Vehicle Create",
   save : "Save",
   update : "Update",
   vehicle_update : "Vehicle Update",

   vehicle_detail : "Vehicle Detail",
   towing_request_details : "Towing Request Details",
   short_export_information : "Short Export Information",
   vehicle_photos : "Vehicle Photos",
   vehicle_documents : "Vehicle Documents",
   vehicle_invoices : "Vehicle Invoices",
   vehicle_condition : "Vehicle Condition",
   download : "Download",
   vheicle_photo_gallery : "Vehicle Photo Gallery",

   loading_date : "Loading Date",
   export_date : "Export Date",
   eta : "Eta",
   booking_no : "Booking No",
   ship_number : "Manifest Number",
   export_excel : "Export Excel",
   inside_the_port_date : "Inside The Port Date",
   export_global_search : "Export Global Search",

   export_create : "Export Create",
   export_update : "Export Update",
   update_destination_export : "Destination Export Create",
   create_destination_export : "Destination Export Update",

   export_document : "CMR doc",
   export_photos : "CMR Photos",
   export_vehicle : "Export Vehcle",
   customer_information : "Customer Information",
   export_details : "Export Details",
   destination_export_detail : "Destination Export Detail",
   bill_of_loading : "Bill Of Loading",
   port_loading_global_search : "Port Loading Global Search",

   user_name : "User Name",
   users : "Users",
   role_name : "Role Name",
   permission : "Permission",
   status_change : "Status Change",
   user_form : "User Form",
   country_form : "Country Form",
   state_form : "State Form",
   city_form : "City Form",
   location_form : "Location Form",
   title : "Title",
   short_code : "Short Code",
   country : "Country",
   global_search : "Global Search",
   

 },
 rn: {
    dashboard:"приборная доска",
    customers:"клиенты",
    vehicles:"транспортные средства",
   export_to_transit:"Экспорт в транзит",
   export_to_destination:"Экспорт в место назначения",
   accounting:"Бухгалтерский учет",
   settings:"Настройки",
   galaxy_ports:"Порты Галактики",
   vehicle_search_by_vin:"Vehicle search by Vin/Lot/Container No",
   locations : "Locations",
   countries : "Countries",
   states : "States",
   cities : "Cities",
   roles : "Roles",
   user_management : "User Management",
   port_of_loading : "Port of Loading",
   port_of_discharge : "Port of Discharge",

   vehicle_status : "Vehicle Status",
   location : "Location",
   all_vehicle : "All Vehicle",
   arrived_to_destination : "Arrived to Destination",
   arrived_to_transit : "Arrived to Transit",
   inside_the_port : "Inside The Port",
   car_on_hand : "Car On Hand",
   shipped_to_transit : "Shipped To Transit",

   customer_global_search : "Customer Global Search",
   search : "поиск",
   add_new : "Add New",
   export_customer : "Export Customer",
   customer_id	 : "Customer Id	",
   name	 : "Name",
   company_name	 : "Company Name",
   email	 : "Email",
   phone_uae	 : "Phone UAE",
   city	 : "City",
   status	 : "Status",
   total_vehicles	 : "Total Vehicles",
   action	 : "действие",
   note_allow_show	 : "You are not allowed to view this page",

   export_vehicles : "Export Vehicls",
   notes : "Notes",
   vehicle_global_search : "Vehicle Global Search",
   photo : "Photo",
   total_photos : "Total Photos",
   add : "Add",
   req_date : "REQ DATE",
   pickup_date : "PICKUP DATE",
   dely_date : "DELY DATE",
   received_date : "Received Date",
   days : "Days",
   year : "Year",
   make : "Make",
   model : "Model",
   color : "Color",
   vin : "Vin",
   lot_number : "Lot Number",
   keys : "Keys",
   vehicle_type : "Vehicle Type",
   created_date : "Created Date",
   note : "Note",

   vehicle_create : "Vehicle Create",
   save : "вставлять",
   update : "Обновить",
   vehicle_update : "Vehicle Update",

   vehicle_details : "Vehicle Details",
   towing_request_details : "Towing Request Details",
   short_export_information : "Short Export Information",
   vehicle_photos : "Vehicle Photos",
   vehicle_documents : "Vehicle Documents",
   vehicle_invoices : "Vehicle Invoices",
   vehicle_condition : "Vehicle Condition",
   download : "скачать",
   vheicle_photo_gallery : "Vehicle Photo Gallery",

   loading_date : "Loading Date",
   export_date : "Export Date",
   eta : "Eta",
   booking_no : "Booking No",
   ship_number : "Ship Number",
   export_excel : "Export Excel",
   inside_the_port_date : "Inside The Port Date",
   export_global_search : "Export Global Search",

   export_create : "Export Create",
   export_update : "Export Update",
   update_destination_export : "Destination Export Create",
   create_destination_export : "Destination Export Update",

   export_document : "Export Documents",
   export_photos : "Export Photos",
   export_vehicle : "Export Vehcle",
   customer_information : "Customer Information",
   export_details : "Export Details",
   destination_export_details : "Destination Export Details",
   bill_of_loading : "Bill Of Loading",
   port_loading_global_search : "Port Loading Global Search",

   user_name : "User Name",
   users : "Users",
   role_name : "Role Name",
   permission : "Permission",
   status_change : "Status Change",
   user_form : "User Form",
   country_form : "Country Form",
   state_form : "State Form",
   city_form : "City Form",
   location_form : "Location Form",
   title : "Title",
   short_code : "Short Code",
   country : "Country",
   global_search : "Global Search",

 }
});

export default languageStrings;